# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1073, 629)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:rgb(17,17,17);\n"
"border-radius:10px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_superior.setStyleSheet("QFrame{\n"
"background-color:rgb(17,17,17);\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius:18px;\n"
"background-color:rgb(17,17,17);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(44,44,44);\n"
"}\n"
"\n"
"")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(10, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(635, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.boton_minimizar = QtWidgets.QPushButton(self.frame_superior)
        self.boton_minimizar.setMinimumSize(QtCore.QSize(38, 38))
        self.boton_minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("iconos/Imagen3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_minimizar.setIcon(icon)
        self.boton_minimizar.setIconSize(QtCore.QSize(36, 36))
        self.boton_minimizar.setObjectName("boton_minimizar")
        self.horizontalLayout.addWidget(self.boton_minimizar)
        self.boton_maximizar = QtWidgets.QPushButton(self.frame_superior)
        self.boton_maximizar.setMinimumSize(QtCore.QSize(38, 38))
        self.boton_maximizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("iconos/Imagen5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_maximizar.setIcon(icon1)
        self.boton_maximizar.setIconSize(QtCore.QSize(36, 36))
        self.boton_maximizar.setObjectName("boton_maximizar")
        self.horizontalLayout.addWidget(self.boton_maximizar)
        self.boton_normalizar = QtWidgets.QPushButton(self.frame_superior)
        self.boton_normalizar.setMinimumSize(QtCore.QSize(38, 38))
        self.boton_normalizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("iconos/Imagen2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_normalizar.setIcon(icon2)
        self.boton_normalizar.setIconSize(QtCore.QSize(36, 36))
        self.boton_normalizar.setObjectName("boton_normalizar")
        self.horizontalLayout.addWidget(self.boton_normalizar)
        self.boton_salir = QtWidgets.QPushButton(self.frame_superior)
        self.boton_salir.setMinimumSize(QtCore.QSize(38, 38))
        self.boton_salir.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("iconos/Imagen1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_salir.setIcon(icon3)
        self.boton_salir.setIconSize(QtCore.QSize(36, 36))
        self.boton_salir.setObjectName("boton_salir")
        self.horizontalLayout.addWidget(self.boton_salir)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("background-color:rgb(40,40,40);\n"
"border-radius:10px")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setStyleSheet("color: rgb(146,208,80);\n"
"font:87 12pt \"cooper black\"")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.comboBox_puerto = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_puerto.setStyleSheet("QComboBox{\n"
"    border: 3px solid #111111;\n"
"    border-radius:5px;\n"
"    min-width:6em;\n"
"    color:rgb(218,0,55);\n"
"    font:87 10pt \"cooper black\";\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    subcontrol-origin:padding;\n"
"    subcontrol-position:top right;\n"
"    width: 15px;\n"
"    border-left-width:3px;\n"
"    border-left-color:#111111;\n"
"    border-left-style:solid;\n"
"    border-top-right-radius:4px;\n"
"    border-bottom-right-radius:4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background: #2c2c2c;\n"
"    selection-background-color: #ff0037;\n"
"    color:#111111;\n"
"}")
        self.comboBox_puerto.setObjectName("comboBox_puerto")
        self.verticalLayout_7.addWidget(self.comboBox_puerto)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setStyleSheet("color: rgb(146,208,80);\n"
"font:87 12pt \"cooper black\"")
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_baudrate.setStyleSheet("QComboBox{\n"
"    border: 3px solid #111111;\n"
"    border-radius:5px;\n"
"    min-width:6em;\n"
"    color:rgb(218,0,55);\n"
"    font:87 10pt \"cooper black\";\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    subcontrol-origin:padding;\n"
"    subcontrol-position:top right;\n"
"    width: 15px;\n"
"    border-left-width:3px;\n"
"    border-left-color:#111111;\n"
"    border-left-style:solid;\n"
"    border-top-right-radius:4px;\n"
"    border-bottom-right-radius:4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background: #2c2c2c;\n"
"    selection-background-color: #ff0037;\n"
"    color:#111111;\n"
"}")
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.verticalLayout_7.addWidget(self.comboBox_baudrate)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7.addWidget(self.frame_8)
        self.boton_conectar = QtWidgets.QPushButton(self.frame_3)
        self.boton_conectar.setMinimumSize(QtCore.QSize(0, 30))
        self.boton_conectar.setStyleSheet("QPushButton{\n"
"    background-color:rgb(146,208,80);\n"
"    font:87 12pt \"cooper black\";\n"
"    color:rgb(17,17,17);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(17,17,17);\n"
"    font:87 12pt \"cooper black\";\n"
"    color:rgb(146,208,80);\n"
"}")
        self.boton_conectar.setObjectName("boton_conectar")
        self.verticalLayout_7.addWidget(self.boton_conectar)
        self.boton_actualizar = QtWidgets.QPushButton(self.frame_3)
        self.boton_actualizar.setMinimumSize(QtCore.QSize(0, 30))
        self.boton_actualizar.setStyleSheet("QPushButton{\n"
"    background-color:rgb(146,208,80);\n"
"    font:87 12pt \"cooper black\";\n"
"    color:rgb(17,17,17);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(17,17,17);\n"
"    font:87 12pt \"cooper black\";\n"
"    color:rgb(146,208,80);\n"
"}")
        self.boton_actualizar.setObjectName("boton_actualizar")
        self.verticalLayout_7.addWidget(self.boton_actualizar)
        self.boton_desconectar = QtWidgets.QPushButton(self.frame_3)
        self.boton_desconectar.setMinimumSize(QtCore.QSize(0, 30))
        self.boton_desconectar.setStyleSheet("QPushButton{\n"
"    background-color:rgb(146,208,80);\n"
"    font:87 12pt \"cooper black\";\n"
"    color:rgb(17,17,17);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(17,17,17);\n"
"    font:87 12pt \"cooper black\";\n"
"    color:rgb(146,208,80);\n"
"}")
        self.boton_desconectar.setObjectName("boton_desconectar")
        self.verticalLayout_7.addWidget(self.boton_desconectar)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.logo = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(100, 80))
        self.logo.setMaximumSize(QtCore.QSize(100, 80))
        self.logo.setSizeIncrement(QtCore.QSize(0, 0))
        self.logo.setBaseSize(QtCore.QSize(0, 0))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("iconos/Imagen4.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.horizontalLayout_4.addWidget(self.logo)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setStyleSheet("background-color:rgb(40,40,40);\n"
"border-radius:10px")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setStyleSheet("color: rgb(146,208,80);\n"
"font:87 12pt \"cooper black\"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3)
        self.frame_11 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.lineEdit_tamano = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_tamano.setMinimumSize(QtCore.QSize(144, 30))
        self.lineEdit_tamano.setMaximumSize(QtCore.QSize(144, 16777215))
        self.lineEdit_tamano.setStyleSheet("QLineEdit{\n"
"    background-color:rgb(17,17,17);\n"
"    border: 3px solid #92d050;\n"
"    border-radius:5px;\n"
"    min-width:6em;\n"
"    color:rgb(255,208,80);\n"
"    font:87 15pt \"cooper black\";\n"
"}\n"
"\n"
"146,208,80")
        self.lineEdit_tamano.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tamano.setObjectName("lineEdit_tamano")
        self.horizontalLayout_5.addWidget(self.lineEdit_tamano)
        self.label_5 = QtWidgets.QLabel(self.frame_11)
        self.label_5.setMinimumSize(QtCore.QSize(30, 30))
        self.label_5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_5.setStyleSheet("color: rgb(146,208,80);\n"
"font:87 12pt \"cooper black\"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_10.addWidget(self.frame_11)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setStyleSheet("color: rgb(146,208,80);\n"
"font:87 12pt \"cooper black\"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.frame_12 = QtWidgets.QFrame(self.frame_6)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.comboBox_categoria = QtWidgets.QComboBox(self.frame_12)
        self.comboBox_categoria.setMinimumSize(QtCore.QSize(96, 0))
        self.comboBox_categoria.setMaximumSize(QtCore.QSize(174, 16777215))
        self.comboBox_categoria.setStyleSheet("QComboBox{\n"
"    border: 3px solid #111111;\n"
"    border-radius:5px;\n"
"    min-width:6em;\n"
"    color:rgb(218,0,55);\n"
"    font:87 10pt \"cooper black\";\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    subcontrol-origin:padding;\n"
"    subcontrol-position:top right;\n"
"    width: 15px;\n"
"    border-left-width:3px;\n"
"    border-left-color:#111111;\n"
"    border-left-style:solid;\n"
"    border-top-right-radius:4px;\n"
"    border-bottom-right-radius:4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background: #2c2c2c;\n"
"    selection-background-color: #ff0037;\n"
"    color:#111111;\n"
"}")
        self.comboBox_categoria.setObjectName("comboBox_categoria")
        self.horizontalLayout_6.addWidget(self.comboBox_categoria)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_10.addWidget(self.frame_12)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem6)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setStyleSheet("background-color:rgb(40,40,40);\n"
"border-radius:10px")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_5.setSpacing(9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_14 = QtWidgets.QFrame(self.frame_4)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.frame_13 = QtWidgets.QFrame(self.frame_14)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_9 = QtWidgets.QFrame(self.frame_13)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem8)
        self.boton_generar_datos = QtWidgets.QPushButton(self.frame_9)
        self.boton_generar_datos.setMinimumSize(QtCore.QSize(200, 30))
        self.boton_generar_datos.setMaximumSize(QtCore.QSize(267, 16777215))
        self.boton_generar_datos.setStyleSheet("QPushButton{\n"
"    background-color:rgb(146,208,80);\n"
"    font:87 12pt \"cooper black\";\n"
"    color:rgb(17,17,17);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(17,17,17);\n"
"    font:87 12pt \"cooper black\";\n"
"    color:rgb(146,208,80);\n"
"}")
        self.boton_generar_datos.setObjectName("boton_generar_datos")
        self.verticalLayout_9.addWidget(self.boton_generar_datos)
        self.verticalLayout_11.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.boton_borrar_muestra = QtWidgets.QPushButton(self.frame_10)
        self.boton_borrar_muestra.setMinimumSize(QtCore.QSize(140, 30))
        self.boton_borrar_muestra.setMaximumSize(QtCore.QSize(267, 16777215))
        self.boton_borrar_muestra.setStyleSheet("QPushButton{\n"
"    background-color:rgb(146,208,80);\n"
"    font:87 12pt \"cooper black\";\n"
"    color:rgb(17,17,17);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(17,17,17);\n"
"    font:87 12pt \"cooper black\";\n"
"    color:rgb(146,208,80);\n"
"}")
        self.boton_borrar_muestra.setObjectName("boton_borrar_muestra")
        self.verticalLayout_8.addWidget(self.boton_borrar_muestra)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem9)
        self.verticalLayout_11.addWidget(self.frame_10)
        self.horizontalLayout_7.addWidget(self.frame_13)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.verticalLayout_5.addWidget(self.frame_14)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setStyleSheet("background-color:rgb(44,44,44);\n"
"border-radius:10px")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.grafica = QtWidgets.QVBoxLayout()
        self.grafica.setObjectName("grafica")
        self.verticalLayout_6.addLayout(self.grafica)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Puerto serial"))
        self.label_2.setText(_translate("MainWindow", "baudrate"))
        self.boton_conectar.setText(_translate("MainWindow", "CONECTAR"))
        self.boton_actualizar.setText(_translate("MainWindow", "ACTUALIZAR"))
        self.boton_desconectar.setText(_translate("MainWindow", "DESCONECTAR"))
        self.label_3.setText(_translate("MainWindow", "Tamaño"))
        self.label_5.setText(_translate("MainWindow", "cm"))
        self.label_4.setText(_translate("MainWindow", "Categoria"))
        self.boton_generar_datos.setText(_translate("MainWindow", "Generar datos"))
        self.boton_borrar_muestra.setText(_translate("MainWindow", "Borrar muestra"))
